apiVersion: v1
kind: Service
metadata:
  name: easy-shopping-frontend
spec:
  type: LoadBalancer
  selector:
    app: easy-shopping-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http